CREATE DATABASE IF NOT EXISTS synergy_php CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE synergy_php;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(256) NOT NULL, login VARCHAR(64) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL);
