import edu.synergy.algorithms.linear.*;import edu.synergy.algorithms.arrays.*;import edu.synergy.algorithms.lists.*;import edu.synergy.algorithms.recursion.*;import edu.synergy.algorithms.quicksort.*;import edu.synergy.algorithms.queues.*;import edu.synergy.algorithms.hash.*;import edu.synergy.algorithms.trees.*;import edu.synergy.algorithms.misc.*;import edu.synergy.algorithms.graphs.*;import edu.synergy.algorithms.finalproject.*;import java.util.*;import java.nio.file.*;
public final class AlgorithmsTest {static int n=0;static void ok(boolean v,String m){n++;if(!v)throw new AssertionError(m);}public static void main(String[]args)throws Exception{
 ok(LinearAlgorithms.findMinValue(new double[]{3,-1,2})==-1,"min");ok(LinearAlgorithms.findMaxValue(new double[]{3,-1,2})==3,"max");ok(LinearAlgorithms.findAverageValue(new double[]{2,4})==3,"avg");ok("B".equals(LinearAlgorithms.findStudentMaxGrade(Map.of("A",new int[]{2,3},"B",new int[]{5,5}))),"best");ok(Arrays.equals(LinearAlgorithms.removeElement(new int[]{1,2,1},1),new int[]{2}),"remove");
 ok(Arrays.equals(ArrayAlgorithms.binarySearch(new int[]{1,3,5,7,9,11},8),new int[]{0,4})||Arrays.equals(ArrayAlgorithms.binarySearch(new int[]{1,3,5,7,9,11},8),new int[]{1,5}),"diff");ok(ArrayAlgorithms.binarySearch(new String[]{"apple","pear","plum"},"pear")==1,"binary");ok(Arrays.equals(ArrayAlgorithms.getClosestLowerNumberDec(new int[]{3,1,2,0,8,4,1,2,5,5}),new int[]{3,1,2,0,8,2,5,5,4,1}),"perm");
 MyLinkedList list=new MyLinkedList();for(int v:new int[]{1,2,3,4,5})list.add(v);ok(list.findMiddle().data==3,"middle");java.io.ByteArrayOutputStream listOut=new java.io.ByteArrayOutputStream();list.printReverse(new java.io.PrintStream(listOut));ok(listOut.toString().trim().equals("5 4 3 2 1"),"reverse list");var sorted=StudentSorter.selectionSortByAsc(new StudentSorter.Student[]{new StudentSorter.Student(5,"A"),new StudentSorter.Student(2,"B")});ok(sorted.getFirst().getPoint()==2,"selection");
 ok(RecursionStack.calculateSum(10)==55,"sum");ok(RecursionStack.range(3,1).equals("3 2 1"),"range");ok(RecursionStack.validBrackets("{[()]}")&&!RecursionStack.validBrackets("([)]"),"brackets");
 java.io.ByteArrayOutputStream digitOut=new java.io.ByteArrayOutputStream();CallStackAlgorithms.printReverseDigits(123,new java.io.PrintStream(digitOut));ok(digitOut.toString().equals("3 2 1"),"digits");ok(CallStackAlgorithms.palindrome("radar")&&!CallStackAlgorithms.palindrome("java"),"palindrome");FootballTeam[]teams={new FootballTeam("A",8),new FootballTeam("B",2),new FootballTeam("C",5)};TeamQuickSort.sort(teams);ok(teams[0].goalCountBySeason()==2&&teams[2].goalCountBySeason()==8,"quick");
 Queue<Integer>q1=new ArrayDeque<>(List.of(123,9,0)),q2=new ArrayDeque<>(List.of(1,-9,10,88,100,1));ok(new ArrayList<>(QueueAlgorithms.interleave(q1,q2)).equals(List.of(123,1,9,-9,0,10,88,100,1)),"queues");var desk=new QueueAlgorithms.CashDesk<String>();desk.addCustomer("A");desk.addCustomer("B");ok("A".equals(desk.serveCustomer()),"fifo");
 HashAlgorithms h=new HashAlgorithms();h.addStudent("A");h.addGrade("A",5);h.addGrade("A",3);ok(h.getAverageGrade("A")==4,"hash avg");ok(HashAlgorithms.frequencies(new int[]{1,1,2}).get(1)==2,"freq");ok(HashAlgorithms.averageUntilZero(new Scanner("20 30 0"))==25,"input avg");
 BinarySearchTree bst=new BinarySearchTree();for(int v:new int[]{5,3,7,6,8})bst.insert(v);ok(bst.search(7)!=null,"tree search");bst.delete(7);ok(bst.search(7)==null&&bst.search(6)!=null&&bst.search(8)!=null,"tree delete");ok(BookShelves.getBookAndNumber(Map.of(4,"Ангелы и демоны",2,"Вишневый сад")).get("Вишневый сад")==2,"shelves");
 ok(MiscAlgorithms.holes(157892)==3,"holes");ok(MiscAlgorithms.fibonacciPosition(13)==7,"fib");ok(GraphRepresentations.task1Matrix().length==4&&GraphRepresentations.task3AdjacencyList().get(3).equals(List.of(2,5))&&GraphRepresentations.task4AdjacencyList().get(0).equals(List.of(1,2)),"graphs");
 Path info=Path.of("final-project/info.json");StudentJsonRepository repo=new StudentJsonRepository();Student[]students=repo.read(info).students();ok(students.length==8,"json count");StudentAlgorithms.quickSort(students);for(int i=1;i<students.length;i++)ok(students[i-1].grade()<=students[i].grade(),"sorted");Student golden=StudentAlgorithms.binarySearchGrade(students,10);ok(golden!=null&&golden.grade()==10,"golden");Path result=Files.createTempFile("students-",".json");repo.write(result,golden,StudentAlgorithms.groupByGrade(students));String output=Files.readString(result);Files.delete(result);ok(output.indexOf("\"goldenStudent\"")<output.indexOf("\"grades\""),"golden first");
 System.out.println("CA-ALGORITHMS tests: "+n+" checks OK");}}
